todo/urls.py
from django.contrib import admin
from django.urls import path
from viewtasks import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    # path('add/', views.add, name='add'),
    path('update/<int:task_id>/', views.update, name='update'),
    path('delete/<int:task_id>/', views.delete, name='delete'),
    path('deletecomp/<int:task_id>/', views.deletecompleted, name='deletecompleted'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.loginout, name='logout'),
]

viewtasks/models.py
from django.db import models

# Create your models here.

class Task(models.Model):
	"""docstring for Task"""
	title = models.CharField(max_length=300)
	complete = models.BooleanField(default=False)

	def __str__(self):
		return self.title

class TaskCompleted(models.Model):
	"""docstring for TaskCompleted"""
	title_completed = models.CharField(max_length=300)

	def __str__(self):
		return self.title_completed

	
		
		


	

viewtasks/forms.py
from django.forms import ModelForm
from .models import Task
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class TaskForm(ModelForm):
	"""docstring for TaskForm"""
	title = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Add new task...'}))

	class Meta:
		model = Task
		fields = '__all__'

class SignUpForm(UserCreationForm):
	class Meta:
		model = User
		fields = ['username', 'password1', 'password2', 'email']
	

			
		

viewtasks/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from .models import Task, TaskCompleted
from .forms import *
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, logout
from django.contrib import messages
from django.contrib.auth import login as dj_login


# Create your views here.

def home(request):
	tasks = Task.objects.all()
	tasks_completed = TaskCompleted.objects.all()
	form = TaskForm()
	if request.method=='POST':
	 	form = TaskForm(request.POST)
	 	if form.is_valid():
	 		form.save()
	 	return redirect('/')
	for task in tasks:
		if  task.complete==True:
			task_complete = TaskCompleted(title_completed=task.title)
			task.delete()
			task_complete.save()
			return redirect('/')
	# try:
	#  	for i in tasks:
	#  		if i.complete==True:
	#  			a.append(i.title)
	# except Exception as e:
	#  	return redirect('/')

	dictionary = {'tasks':tasks, 'form':form, 'tasks_completed': tasks_completed}
	return render(request,'home.html', dictionary)

def update(request, task_id):
	task = Task.objects.get(id=task_id)
	form = TaskForm(instance=task)
	if request.method=='POST':
	 	form = TaskForm(request.POST, instance=task)
	 	if form.is_valid():
	 		form.save()
	 		return redirect('/')

	dictionary = {'task':task, 'form':form}
	return render(request, 'update.html', dictionary)

def delete(request,task_id):
	task = Task.objects.get(id=task_id)
	task.delete()
	return redirect('/')

def deletecompleted(request,task_id):
	task = TaskCompleted.objects.get(id=task_id)
	task.delete()
	return redirect('/')

def signup(request):
	if request.method == 'POST':
		form = SignUpForm(request.POST)
		if form.is_valid():
			form.save()
	else:
		form = SignUpForm()

	dictionary = {'form':form}
	return render(request, 'signup.html', dictionary)

def login(request):
	if request.method == 'POST':
		form = AuthenticationForm(data=request.POST)
		if form.is_valid():
			username = request.POST.get('username')
			password = request.POST.get('password')
			user = authenticate(request, username=username, password=password)
			if user is not None:
				dj_login(request, user)
				return redirect('/')
			else:
				messages.add_message(request, messages.INFO, 'Hello world.')
	else:
		form = AuthenticationForm()
			
	return render(request, 'login.html')

def loginout(request):
	logout(request)
	return HttpResponseRedirect('/login/')






# def add(request):
# 	task = Task(title=request.POST['add'])
# 	task.save()
# 	return HttpResponseRedirect('../')

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
	<style>
		.center-column{
			width: 600px;
			background-color: #fff;
			margin: 20px;
			margin-top: 50px;
			padding: 20px;
			border-radius: 3px;
			box-shadow: 6px 2px 30px 0px rgba(0,0,0,0.75);
		}

		body{
			background-color: #638CB8;
		}

		.aaa{
			width: 100%;
			padding: 12px 20px;
			margin: 8px 0;
			box-sizing: border-box;
		}

		#id_title{
			width: 100%;
		}

		.item-row{
			background-color: #906abd;
			margin: 10px;
			padding: 20px;
			border-radius: 3px;
			color: #fff;
			font-size: 16px;
			box-shadow: 0px -1px 10px -4px rgba(0,0,0,0.75);
		}

		.wow{
			margin-top: 7px;
			margin-bottom: 10px;
		}

		/*.cart-icon{
			float: right;
    		text-decoration: none;
    		color: #fff;
		}*/
		.material-icons {
			color: black;
			float: right;
			font-family: 'Material Icons';
			font-weight: bold;
			font-style: initial;
			font-size: 25px;  /* Preferred icon size */
			display: inline-block;
			line-height: 1;
			text-transform: ;
			letter-spacing: normal;
			word-wrap: normal;
			white-space: nowrap;
			direction: ltr;

			/* Support for all WebKit browsers. */
			-webkit-font-smoothing: antialiased;
			/* Support for Safari and Chrome. */
			text-rendering: optimizeLegibility;

			/* Support for Firefox. */
			-moz-osx-font-smoothing: grayscale;

			/* Support for IE. */
			font-feature-settings: 'liga';
			}

		.cart-icon:hover {
		  	color: white;
		}

		.sign{
			width: 600px;
			background-color: #fff;
			margin-top: 50px;
			padding: 20px;
			border-radius: 3px;
			box-shadow: 6px 2px 30px 0px rgba(0,0,0,0.75);
		}

		.btn-lg{
			margin-left: 5px;
		}


	</style>
</head>
<body>
<div class="container">
	<div class="row">
        <div class="col-6">
			<div class="center-column">
				<div class="item-row d-flex justify-content-center">
				{% if request.user.is_authenticated and request.user.username%}
				<a href="/"><button type="button" class="btn btn-lg btn-outline-light ">Welcome, {{request.user.username}}</button></a>
				<a href="/logout/"><button type="button" class="btn btn-lg btn-outline-light">LOGOUT</button></a>
				{%else%}
				<a href="/signup/"><button type="button" class="btn btn-lg btn-outline-light">SIGN UP</button></a>
				<a href="/login/"><button type="button" class="btn btn-lg btn-outline-light">LOGIN</button></a>
				{%endif%}
				</div>
				<div class="white-text text-center wow fadeInUp"><strong><h3>TODO APP</h3></strong></div>
					<form action="/" method="POST">
						{% csrf_token %}
						{{form.title}}
						<input class="btn btn-info aaa" type="submit" value="Add">
					</form>

		<!-- <form action="" method="POST">{% csrf_token %}
			<input type="text" name="add" placeholder="Enter the text">
			<input type="submit" value="Add">
		</form> -->
				<div class="todo-list">
				{% for task in tasks %}
					<div class="item-row">
						<a href="/update/{{task.id}}/"><input class="btn btn-info btn-sm" type="submit" value="UPDATE"></a>
						<a href="/delete/{{task.id}}/"><input class="btn btn-danger btn-sm" type="submit" value="DELETE"></a>
						<span>{{task.title}}</span>
					
					</div>
				{% endfor %}
				</div>
			</div>
		</div>
        <div class="col-6">
			<div class="center-column">
				<div class="white-text text-center wow fadeInUp"><strong><h3>COMPLETED TASKS</h3></strong></div>
					<div class="todo-list">
						{% for task in tasks_completed %}
						<div class="item-row">
							<b><strike>{{task}}</strike></b>
							<a href="/deletecomp/{{task.id}}/"><i class="material-icons cart-icon">clear</i></a>
							<!-- {% if task.complete == True %}
								<strike>{{task.title}}</strike>
							
							{% else %}
								<span>{{task.title}}</span>
							{% endif %} -->
						</div>
						{% endfor %}
					</div>
			</div>
		</div>
	</div>
</div>

<footer class="text-dark mt-5 p-5">
    <div class="container">
        <p class="lead text-center">
            Copyright &copy; 2020 TODO APP
        </p>
    </div>
</footer>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>
				</div>
				{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'signup' %}" class="ml-2">Sign Up</a>
					</div>
			
				</div>
			</div>
		</div>
	</div>
</body>

</html>

templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
</head>
<body>
	<h2>SignUP</h2>
	
</body>
</html>

templates/update.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons"
    rel="stylesheet">
    <style>
    	.center-column{
			width: 500px;
			background-color: #fff;
			margin: 20px auto;
			margin-top: 50px;
			padding: 20px;
			border-radius: 3px;
			box-shadow: 6px 2px 30px 0px rgba(0,0,0,0.75);
		}

		body{
			background-color: #638CB8;
		}

		.aaa{
			width: 100%;
			padding: 12px 20px;
			margin: 8px 0;
			box-sizing: border-box;
		}

		#id_title{
			width: 100%;
		}

		.item-row{
			background-color: #906abd;
			margin: 10px;
			padding: 20px;
			border-radius: 3px;
			color: #fff;
			font-size: 16px;
			box-shadow: 0px -1px 10px -4px rgba(0,0,0,0.75);
		}

		.wow{
			margin-top: 7px;
			margin-bottom: 10px;
		}

		form{
			background-color: #906abd;
			margin: 10px;
			padding: 20px;
			border-radius: 3px;
			color: #fff;
			font-size: 16px;
			box-shadow: 0px -1px 10px -4px rgba(0,0,0,0.75);
		}

		label{
			font-weight: bold;
		}

    </style>
</head>
<body>
	<div class="center-column">
		<div class="white-text text-center wow fadeInUp"><strong><h3>UPDATE TASK "{{task.title}}"</h3></strong></div>
		<form action="" method="POST">
			{% csrf_token %}
			{{form}}
			<input type="submit" value="Update" class="btn btn-info aaa">
		</form>
	</div>
</body>
</html>